version: "3.6"
services:
  # mula:
  #   container_name: mula
  #   build: ./mula-backend/backend/
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./mula-backend/backend/.env
  #   restart: always
  # nginx-webserver:
  #   build: ./nginx-webserver
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9002:9002"
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    deploy:
      resources:
        limits:
          cpus: "0.50"
  graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    ports:
      - "9090:9090"
    restart: always
    extra_hosts: 
     - host.docker.internal:host-gateway
    environment:
      ENV_VAR: host.docker.internal:3002
      HASURA_GRAPHQL_SERVER_PORT: 9090
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: axra_48b59ff9b4139e7d
      HASURA_GRAPHQL_DISABLE_CORS: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"Cast from ten bronze cannons, it was unveiled on April 19, 1875, during the centennial celebration of the Battle of Concord"}'
volumes:
  db_data:
