name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd offiline-bonchon-erp/bonchon-offline-backend
            git pull https://${{ secrets.SERVER_GIT_USERNAME }}:${{ secrets.SERVER_TOKEN }}@github.com/AxraTech/bonchon-offline-backend.git
            cd ../
            docker compose build
            docker compose up -d
            docker system prune -af
